services:
  postgres:
    image: postgres:17.7-trixie
    container_name: sc2pulse-postgresql-prod
    networks:
      - sc2pulse_net_prod
    volumes:
      - sc2pulse_data_prod:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sc2pulse
      - POSTGRES_USER=sc2pulse
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sc2pulse -d sc2pulse" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  sc2pulse:
    image: ghcr.io/sc2-pulse/sc2-pulse:2
    container_name: sc2pulse-prod
    networks:
      - sc2pulse_net_prod
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sc2pulse?reWriteBatchedInserts=true
      - SPRING_DATASOURCE_USERNAME=sc2pulse
      - SPRING_PROFILES_ACTIVE=default,prod
      - COM_NEPHEST_BATTLENET_SC2_CRON_ENABLED=true
    restart: unless-stopped
networks:
  sc2pulse_net_prod:
    driver: bridge
volumes:
  sc2pulse_data_prod: