infisical:
  exit-after-auth: true
  address: https://app.infisical.com
auth:
  type: universal-auth
  config:
    client-id: /etc/sc2pulse/id
    client-secret: /etc/sc2pulse/secret
    remove_client_secret_on_read: false
templates:
  - source-path: /etc/sc2pulse/template.tmpl
    destination-path: "/run/all-secrets.txt"
