services:
  infisical:
    image: infisical/cli:0.43.46
    container_name: infisical-prod
    networks:
      - sc2pulse_net_prod
    volumes:
      - ./containers/secrets/infisical/agent-config.yaml:/opt/sc2pulse/agent-config.yaml:ro
      - ./containers/secrets/infisical/template.tmpl:/opt/sc2pulse/template.tmpl:ro
      - ./containers/secrets/infisical/entrypoint.sh:/entrypoint.sh:ro
      - /dev/shm/sc2pulse/sc2pulse:/run/sc2pulse
      - /dev/shm/sc2pulse/postgres:/run/postgres
      - /dev/shm/sc2pulse/clickhouse:/run/clickhouse
    entrypoint: ["/entrypoint.sh"]
  sc2pulse:
    environment:
      - SPRING_CONFIG_IMPORT=optional:configtree:/run/sc2pulse/
    depends_on:
      infisical:
        condition: service_completed_successfully
    volumes:
      - /dev/shm/sc2pulse/sc2pulse:/run/secrets
  postgres:
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/spring.datasource.password
    depends_on:
      infisical:
        condition: service_completed_successfully
    volumes:
      - /dev/shm/sc2pulse/postgres:/run/secrets
  clickhouse:
    environment:
      - CLICKHOUSE_PASSWORD_FILE=/run/secrets/spring.datasource.password
    depends_on:
      infisical:
        condition: service_completed_successfully
    volumes:
      - /dev/shm/sc2pulse/clickhouse:/run/secrets
