services:
  infisical:
    image: infisical/cli:0.43.46
    container_name: infisical-prod
    networks:
      - sc2pulse_net_prod
    volumes:
      - ./containers/secrets/infisical/agent-config.yaml:/etc/sc2pulse/agent-config.yaml:ro
      - ./containers/secrets/infisical/template.tmpl:/etc/sc2pulse/template.tmpl:ro
      - ./containers/secrets/infisical/entrypoint.sh:/entrypoint.sh:ro
      - sc2pulse_secret_volume:/run/sc2pulse
      - postgres_secret_volume:/run/postgres
    entrypoint: ["/entrypoint.sh"]
    restart: on-failure
  sc2pulse:
    environment:
      - SPRING_CONFIG_IMPORT=optional:configtree:/run/sc2pulse/
    depends_on:
      infisical:
        condition: service_completed_successfully
    volumes:
      - sc2pulse_secret_volume:/run/secrets
  postgres:
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/spring.datasource.password
    depends_on:
      infisical:
        condition: service_completed_successfully
    volumes:
      - postgres_secret_volume:/run/secrets
volumes:
  sc2pulse_secret_volume:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  postgres_secret_volume:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
