# Copyright (C) 2020-2026 Oleksandr Masniuk
# SPDX-License-Identifier: AGPL-3.0-or-later

spring.datasource.driver-class-name=org.postgresql.Driver
com.nephest.battlenet.sc2.datasource.native.clickhouse.username=${spring.datasource.username}
com.nephest.battlenet.sc2.datasource.native.clickhouse.password=${spring.datasource.password}
server.error.whitelabel.enabled=false
server.servlet.session.persistent=false
spring.task.scheduling.pool.size=5
spring.jdbc.getParameterType.ignore=true
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=20000,expireAfterWrite=7d
com.nephest.battlenet.sc2.useragent=SC2Pulse (${com.nephest.battlenet.sc2.url.public:http://127.0.0.1/}#{environment['com.nephest.battlenet.sc2.contacts.email'] > '' ? ';' + environment['com.nephest.battlenet.sc2.contacts.email'] : ''})
com.nephest.battlenet.sc2.ladder.alternative.regions=
com.nephest.battlenet.sc2.ladder.regions=US,EU,KR
com.nephest.battlenet.sc2.player.complaint.policy.link=https://github.com/nephest/sc2-pulse/wiki/Player-complaint-policy
springdoc.swagger-ui.path=/doc/api
springdoc.swagger-ui.showCommonExtensions=true
