# Copyright (C) 2020-2026 Oleksandr Masniuk
# SPDX-License-Identifier: AGPL-3.0-or-later

spring.security.oauth2.client.provider.discord=discord
spring.security.oauth2.client.provider.discord.authorization-uri=https://discord.com/api/v10/oauth2/authorize
spring.security.oauth2.client.provider.discord.token-uri=https://discord.com/api/v10/oauth2/token
spring.security.oauth2.client.provider.discord.user-info-uri=https://discord.com/api/v10/users/@me
spring.security.oauth2.client.provider.discord.userNameAttribute=id

spring.security.oauth2.client.registration.discord-lg=discord-lg
spring.security.oauth2.client.registration.discord-lg.provider=discord
spring.security.oauth2.client.registration.discord-lg.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.discord-lg.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.discord-lg.scope=identify, role_connections.write, guilds
spring.security.oauth2.client.registration.discord-lg.redirect-uri=${com.nephest.battlenet.sc2.url.public:localhost}login/oauth2/code/discord-lg
spring.security.oauth2.client.registration.discord-lg.client-name=Discord
spring.security.oauth2.client.registration.discord-lg.client-id=${spring.security.oauth2.client.discord.client-id}
spring.security.oauth2.client.registration.discord-lg.client-secret=${spring.security.oauth2.client.discord.client-secret}
