# Copyright (C) 2020-2026 Oleksandr Masniuk
# SPDX-License-Identifier: AGPL-3.0-or-later

spring.security.oauth2.client.provider.twitch=twitch
spring.security.oauth2.client.provider.twitch.issuer-uri=https://id.twitch.tv/oauth2

spring.security.oauth2.client.registration.twitch-sys=twitch-sys
spring.security.oauth2.client.registration.twitch-sys.provider=twitch
spring.security.oauth2.client.registration.twitch-sys.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.twitch-sys.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.twitch-sys.client-id=${spring.security.oauth2.client.twitch.client-id}
spring.security.oauth2.client.registration.twitch-sys.client-secret=${spring.security.oauth2.client.twitch.client-secret}
