limit_req_zone $binary_remote_addr zone=all:10m rate=200r/s;
limit_req_zone $binary_remote_addr zone=apiall:10m rate=4r/s;
limit_req_status 429;

map $http_origin $allow_origin {
    https://sc2-pulse.github.io $http_origin;
    default "";
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    ssl_certificate /etc/ssl/certs/sc2pulse.pem;
    ssl_certificate_key /etc/ssl/private/sc2pulse.key;
    add_header Strict-Transport-Security "max-age=31536000" always;

    server_tokens off;
    server_name sc2pulse.nephest.com;
    index index.html index.htm;
    gzip on;
    gzip_types text/html text/css application/javascript application/json;
    gzip_proxied any;

    location / {
        return 307 https://$host/sc2/;
    }

    location /sc2/api/ {
        limit_req zone=apiall burst=30 delay=12;
        add_header RateLimit-Limit "4" always;
        add_header RateLimit-Burst "12" always;
        add_header RateLimit-Reset "1" always;
        add_header 'Access-Control-Allow-Origin' $allow_origin always;
        add_header Vary Origin always;
        include /usr/local/etc/nginx/sc2pulse-proxy.conf;
    }

    location /sc2/ {
        limit_req zone=all burst=200;
        include /usr/local/etc/nginx/sc2pulse-proxy.conf;
    }

}
server {
    if ($host = sc2pulse.nephest.com) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;
    server_name sc2pulse.nephest.com;
    return 404;
}
